Traceback (most recent call last):
  File "search_indexes.py", line 3, in <module>
    from haystack import indexes
  File "/home/sundar/Desktop/tds/ven/local/lib/python2.7/site-packages/haystack/__init__.py", line 10, in <module>
    from haystack.constants import DEFAULT_ALIAS
  File "/home/sundar/Desktop/tds/ven/local/lib/python2.7/site-packages/haystack/constants.py", line 10, in <module>
    ID = getattr(settings, 'HAYSTACK_ID_FIELD', 'id')
  File "/home/sundar/Desktop/tds/ven/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/sundar/Desktop/tds/ven/local/lib/python2.7/site-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting HAYSTACK_ID_FIELD, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
